/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 54ecc75c684e1e9e7d6576a7ac528092)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		BROWSER: Fetcher;
		AI: Ai;
		ASSETS: Fetcher;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		GOAL_PLANNING_WORKFLOW: Workflow<Parameters<import("./src/server").GoalPlanningWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
