/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 34a1ef3d4789d4f3fb166fa71cf88aba)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		BROWSER: Fetcher;
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		GOAL_PLANNING_WORKFLOW: Workflow<Parameters<import("./src/server").GoalPlanningWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
